.TH NETIO_CONTEXT_PRINT 3 2014-08-09 Linux "Linux Programmer's Manual"
.SH NAME
netio_context_print \- print an unpacked network packet
.SH SYNOPSIS
.nf
.B #include <netio/context.h>

.BI "int netio_context_print(netio_context_t *" this, " FILE *" f,
.BI "                        const netio_header_t *" header );
.fi
.sp
Compile and link with \fI\-netio\fP.
.SH DESCRIPTION
The
.BR netio_context_print ()
function start the printing pipeline which print the given list of headers
with the base pointed by
.IR header
into a human readable format on the given file
.IR f .
The print behavior can be modified throught the hook of the context pointed by
.IR this .
.SH RETURN VALUE
On success,
.BR netio_context_print ()
returns 0;
on error, it returns an error number.
.SH SEE ALSO
.BR netio (7),
.BR netio_context_init (3),
.BR netio_context_unpack (3)
